### ISSUE TITLE
Forgotten console.log() in current version in npmjs.com

### ISSUE THREAD

**Issue by Dzhuneyt** [sweatpotato13/etherscan-ts#455]
The currently published version in NPM (1.0.1) seems to include a console.log() on line 1097 (within the `wrapFetch()` function):
<img width="1608" alt="image" src="https://user-images.githubusercontent.com/1754428/218765737-208ca0d9-4d83-46a3-9301-2b16f8ad4972.png">

The source code in the repo doesn't have that console.log() so I assume the published version is based on some older version of the code.

Suggestion is to sync the version in NPM with the repo, so the console.log() is removed.

**Comment by Dzhuneyt** [comment]
@sweatpotato13

**Comment by sweatpotato13** [comment]
Thanks for reporting

I have released version 1.0.2 that fixes the issue.
