### ISSUE TITLE
make api url configurable

### ISSUE THREAD

**Issue by groninge01** [sweatpotato13/etherscan-ts#623]
Hi,

Thanks for this package. It is the most complete and current one I could find.

I wanted to use it for ftmscan though so I forked it and set the api url as a variable in the constructor.
If you want I can create a (very small) PR for it or else I'll just keep on using my own fork.

Greetings from Europe!

**Comment by sweatpotato13** [comment]
Done with [v1.1.0](https://github.com/sweatpotato13/etherscan-ts/releases/tag/v1.1.0)

thanks to contribute
